### ISSUE TITLE
Dynamic className that changes when it's property does

### ISSUE THREAD

**Issue by Jordan4jc** [asross/dynamic-link#1] opened 2016-02-11 15:29 UTC
I wanted to get the className of a dynamic-link I defined to change to have `active` along with the normal className when a certain property is true, but it seems when the property is changed to true it's not re-computing the className to what I specified. Is there a way to get this behavior to work?

**Comment by asross** [comment] 2016-02-11 15:53
Hmm, can you give an example in code? If there is an update to the component's `params.className` or `className` to `"some-class-name active"` instead of just `"some-class-name"`, it should update the link's HTML.

It's possible there's an issue in how I'm overriding `className` though, or that I'm somehow making it impossible to pass additional class names. If you can provide just a few more details then I should be able to replicate the issue in a test and implement a fix.

**Comment by Jordan4jc** [comment] 2016-02-11 15:58
This is how I tried it `className: this.get('filteringLosing') ? "filter-losing active" : "filter-losing"`

**Comment by asross** [comment] 2016-02-11 16:49
> This is how I tried it className: this.get('filteringLosing') ? "filter-losing active" : "filter-losing"

Can you give more context? That doesn't look like a computed property to me, and also where are you putting that logic? Is it in a controller or component whose template invokes `dynamic-link`?

**Comment by Jordan4jc** [comment] 2016-02-11 16:55
In the route I am setting an array of navigation items like so

```
this.get('navigation').set('actionBarItems',[
    Ember.Object.create({
        linkParams:  {
            action: "losingItems",
            className: this.get('filteringLosing') ? "filter-losing active" : "filter-losing"
        },
        icon: "noun_245219_cc"
      }),
    Ember.Object.create({
       linkParams:  {
            action: "winningItems",
            className: "filter-winning"
        },
        icon: "trophy"
    }),
    Ember.Object.create({
        linkParams:  {
            action: "watchingItems",
            className: "filter-watching"
        },
        icon: "noun_197397_cc"
    })
]);
```

I also have a property `filteringLosing: false,` in an action I toggle this property so that it's now true

`this.toggleProperty('filteringLosing');`

Where my navigation is I call `dynamic-link` like

```
{{#dynamic-link params=linkParams}}
    ...
{{/dynamic-link}}
```

**Comment by asross** [comment] 2016-02-11 19:22
Ah, well it looks like the problem is that `actionBarItems` isn't a computed property, so it won't update when `filteringLosing` changes.

One option is to restructure your code so that your `navigation` takes a computed property, which would depend on `filteringLosing`, e.g.:

```javascript
actionBarItems: Ember.computed('filteringLosing', function() {
  return [{
      linkParams:  {
          action: "losingItems",
          className: this.get('filteringLosing') ? "filter-losing active" : "filter-losing"
      },
      icon: "noun_245219_cc"
  }, {
       // rest of your action bar items
  }];
})
```

But I don't know how the rest of your code is structured, so I can't say exactly how you would do this.

Another option is to update `navigation.actionBarItems` using an observer whenever `filteringLosing` changes, which might look like:

```javascript
updateNavigation: Ember.on('init', Ember.observer('filteringLosing', function() {
  this.get('navigation').set('actionBarItems',[
      Ember.Object.create({
          linkParams:  {
              action: "losingItems",
              className: this.get('filteringLosing') ? "filter-losing active" : "filter-losing"
          },
          icon: "noun_245219_cc"
        }),
      Ember.Object.create({
         linkParams:  {
              action: "winningItems",
              className: "filter-winning"
          },
          icon: "trophy"
      }),
      Ember.Object.create({
          linkParams:  {
              action: "watchingItems",
              className: "filter-watching"
          },
          icon: "noun_197397_cc"
      })
  ]);
}))
```
That function will re-trigger every time `filteringLosing` changes, so the link should hopefully update too.

**Comment by Jordan4jc** [comment] 2016-02-11 19:24
I'm also noticing when a property changes and I have the `model` set to the value of that property the links are not being updated on page to point to the new link with the updated model based on the property that changed. 

Basically in the same vein as this above class issue as it seems when that property changes it doesn't update the class, this is happening also in the model definition.

**Comment by asross** [comment] 2016-02-11 19:39
> I'm also noticing when a property changes and I have the model set to the value of that property the links are not being updated on page to point to the new link with the updated model based on the property that changed.
> 
> Basically in the same vein as this above class issue as it seems when that property changes it doesn't update the class, this is happening also in the model definition.

Again, from what you've showed me so far this doesn't seem to be an issue with `dynamic-link`; instead it looks like you're setting `actionBarItems` without any data bindings, so none of the updates ever propagate to `navigation`.

**Comment by asross** [comment] 2016-02-11 19:56
If it's helpful, the pattern I used to get this type of behavior (where you have a bar of links that's present on multiple routes but should be different for each) is to have a named outlet in my application template for the action bar:
```hbs
{{! application.hbs }}

{{ outlet "action-bar" }}
```
Then a partial with my action bar:
```hbs
{{! -action-bar.hbs }}

{{#if actionBarItems}}
  <ul class='action-bar'>
     {{#each actionBarItems as |actionBarItem|}} 
        <li class='action-bar-item'>
          {{#dynamic-link params=actionBarItem.linkParams}}
             {{actionBarItem.linkText}}
          {{/dynamic-link}}
        </li>
     {{/each}}
  </ul>
{{/if}}
```
And then I have a mixin I include in some routes which renders an action bar template:
```javascript
// app/mixins/action-bar-route.js
export default Ember.Mixin.extend({
  renderTemplate: function(controller, model) {
     this.render('action-bar', { into: 'application', outlet: 'action-bar' });
  }
});
```
At that point, for a route where I want the action bar, I just include the mixin and define `actionBarItems` as a computed property on its controller:
```javascript
// app/controllers/some-controller.js
export default Ember.Controller.extend({
  actionBarItems: Ember.computed('model.name', 'filteringLosing', function() {
    return [
      // some list of items that depend on some of my properties
    ];
  });
});
```
That pattern has worked pretty well for me with `dynamic-link`.

**Comment by asross** [comment] 2016-02-16 14:18
Going to close this now since it seems like it's not a problem with `dynamic-link`.

**Closed by asross** 2016-02-16 14:18 UTC
